### ISSUE TITLE
Add a MySQL provider

### ISSUE THREAD

**Issue by damienbod** [damienbod/AspNet5MultipleProject#1]
I would like to add an example of a MySQL Provider.

@SapientGuardian would love to use your code, would you be interested in creating a pull request?

Greetings Damien

**Comment by SapientGuardian** [comment]
Certainly! I'll get one ready later today.

**Comment by damienbod** [comment]
cool, thanks

**Comment by damienbod** [comment]
Hi @SapientGuardian 

I'm having problems with this solution, I get an Exception: There is already an open DataReader when I try to open add some data. Did you experience this?

Greetings Damien

**Comment by damienbod** [comment]
here's a similar exception
http://stackoverflow.com/questions/25128321/there-is-already-an-open-datareader-even-though-it-is-not

**Comment by damienbod** [comment]
{Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. ---> MySql.Data.MySqlClient.MySqlException: There is already an open DataReader associated with this Connection which must be closed first.
   at MySql.Data.MySqlClient.ExceptionInterceptor.Throw(Exception exception)
   at MySql.Data.MySqlClient.MySqlCommand.CheckState()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, String executeMethod, IReadOnlyDictionary`2 parameterValues, Boolean openConnection, Boolean closeConnection)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues, Boolean manageConnection)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at DataAccessMySqlProvider.DomainModelMySqlContext.SaveChanges() in C:\git\damienbod\AspNet5MultipleProject\src\DataAccessMySqlProvider\DomainModelMySqlContext.cs:line 39
   at DataAccessMySqlProvider.DataAccessMySqlProvider.AddDataEventRecord(DataEventRecord dataEventRecord) in C:\git\damienbod\AspNet5MultipleProject\src\DataAccessMySqlProvider\DataAccessMySqlProvider.cs:line 30
   at AspNet5MultipleProject.Controllers.DataEventRecordsController.Post(DataEventRecord value) in C:\git\damienbod\AspNet5MultipleProject\src\AspNet5MultipleProject\Controllers\DataEventRecordsController.cs:line 41
   at Microsoft.AspNetCore.Mvc.Internal.ObjectMethodExecutor.<>c__DisplayClass37_0.<WrapVoidAction>b__0(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionFilterAsync>d__28.MoveNext()}

**Comment by SapientGuardian** [comment]
This was an old bug: https://github.com/SapientGuardian/SapientGuardian.EntityFrameworkCore.MySql/issues/4

Can you check your project.json.lock file to see what version of the library you've got?

**Comment by damienbod** [comment]
"SapientGuardian.MySql.Data": "6.9.811"

**Comment by damienbod** [comment]
Thanks for the hint, works perfect now, updated the project.lock.json

**Comment by damienbod** [comment]
Hi @SapientGuardian 

I'm creating a blog and will publish this later tonight.

Here's the draft:
https://github.com/damienbod/AspNet5MultipleProject/blob/master/src/DataAccessMySqlProvider/readme.md

If you would like to change this, or that I mention you differently, more, or not at all, let me know. 

I could you as an author if you prefer that.

Thanks for your code.

Greetings Damien

**Comment by SapientGuardian** [comment]
Looks great, glad you got it working! I'm a little worried if you had to manually edit your project.lock.json though, since it's a generated file. It should just pull latest when you do a dotnet restore.

**Comment by damienbod** [comment]
I didn't edit this file directly, changed the version to 7.1.4 in project.json and deleted the lock file.

Greetings Damien
